/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "W-kellen的博客",
  "description": "don't stop",
  "base": "/My-blog/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.png",
        "actionText": "Get Started →",
        "actionLink": "/web/",
        "features": [
          {
            "title": "day day up",
            "details": "记录每一天的进步, 一分耕耘，一分收获."
          },
          {
            "title": "W-kellend的前端升级之路",
            "details": "一只前端小白的小破站，记录自己的变(tuo)强(fa)历程"
          },
          {
            "title": "W-kellen",
            "details": "变秃才能变强。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2019-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0ad2a7b9",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端基础",
        "items": [
          {
            "text": "HTML",
            "link": "/web/html/"
          },
          {
            "text": "css",
            "link": "/web/css/"
          },
          {
            "text": "HTML5",
            "link": "/web/H5/"
          },
          {
            "text": "CSS3",
            "link": "/web/C3/"
          }
        ]
      },
      {
        "text": "js",
        "items": [
          {
            "text": "js基础",
            "link": "/JavaScript/js/"
          },
          {
            "text": "进阶",
            "link": "/JavaScript/up/"
          },
          {
            "text": "ES6",
            "link": "/JavaScript/es6/"
          }
        ]
      },
      {
        "text": "vue",
        "link": "/vue/"
      },
      {
        "text": "优秀博客",
        "items": [
          {
            "text": "张鑫旭-鑫空间-鑫生活",
            "link": "https://www.zhangxinxu.com/"
          }
        ]
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2
  }
}